# Generated by Django 6.0 on 2025-12-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
