# Generated by Django 6.0 on 2025-12-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
    ]
